### ISSUE TITLE
国服目前因兼容性问题不能使用

### ISSUE THREAD

**Issue by guilyou** [44451516/XIVSlothCombo#38]
国服目前（2023.05.24）不能使用本插件，卫月提示因兼容性问题无法使用。

**Comment by DGdeath** [comment]
国服卫月作者手动将该插件禁止了

**Comment by zdian** [comment]
可恶 有什么解决方法么？

**Comment by guilyou** [comment]
https://github.com/NightmareXIV/UnbanPluginsCN/releases/tag/2.0.0.0
找到解决办法了，在启动卫月前先启动这个就行了

**Comment by sakuraDan2023** [comment]
> https://github.com/NightmareXIV/UnbanPluginsCN/releases/tag/2.0.0.0 找到解决办法了，在启动卫月前先启动这个就行了

这个办法只适用于Windows，不适用于Mac OS或者Linux或者Steam Deck，其实有一个更简单的办法，下载离线插件，然后把里面的名字改了就能用了
如果要上仓库，建议作者release前可以把插件名字改了，蓝月ban的list是按插件名字匹配的，这样就可以直接上仓库，而不用下载离线插件再改名字了

**Comment by KellySakura** [comment]
> 

你好，请问你的意思是把文件夹名和里面的文件都修改了就可以用了是这个意思吗？

**Comment by KellySakura** [comment]
> > https://github.com/NightmareXIV/UnbanPluginsCN/releases/tag/2.0.0.0 找到解决办法了，在启动卫月前先启动这个就行了
> 
> 这个办法只适用于Windows，不适用于Mac OS或者Linux或者Steam Deck，其实有一个更简单的办法，下载离线插件，然后把里面的名字改了就能用了 如果要上仓库，建议作者release前可以把插件名字改了，蓝月ban的list是按插件名字匹配的，这样就可以直接上仓库，而不用下载离线插件再改名字了


你好，请问你的意思是把文件夹名和里面的文件都修改了就可以用了是这个意思吗？

**Comment by gaoyang385** [comment]
> > > https://github.com/NightmareXIV/UnbanPluginsCN/releases/tag/2.0.0.0 找到解决办法了，在启动卫月前先启动这个就行了
> > 
> > 
> > 这个办法只适用于Windows，不适用于Mac OS或者Linux或者Steam Deck，其实有一个更简单的办法，下载离线插件，然后把里面的名字改了就能用了 如果要上仓库，建议作者release前可以把插件名字改了，蓝月ban的list是按插件名字匹配的，这样就可以直接上仓库，而不用下载离线插件再改名字了
> 
> 你好，请问你的意思是把文件夹名和里面的文件都修改了就可以用了是这个意思吗？

不需要，只需要修改离线插件中，XIVSlothCombo.xml中：
`<assembly>
        <name>XIVSlothCombo</name>
    </assembly>`
修改为
`<assembly>
        <name>combo</name>
    </assembly>`
以及XIVSlothCombo.json中：
`"Name": "XIVSlothCombo"`
修改为：
`"Name": "combo"`
`"InternalName": "XIVSlothCombo"`修改为
`"InternalName": "combo"`

就行了
