### ISSUE TITLE
【建议】国服解禁的办法

### ISSUE THREAD

**Issue by sakuraDan2023** [44451516/XIVSlothCombo#39]
使用解禁软件的这个办法只适用于Windows，不适用于Mac OS或者Linux或者Steam Deck。
其实有一个更简单的办法，下载离线插件，然后把里面的名字改了就能用了。
如果要上仓库，建议作者release前可以把插件名字改了，蓝月ban的list是按插件名字匹配的，这样就可以直接上仓库，而不用下载离线插件再改名字了

**Comment by 44451516** [comment]
已经修改为XIVSlothComboX 注意配置。
找到pluginConfigs里面的XIVSlothCombo.json 重命名为XIVSlothComboX.json
