### ISSUE TITLE
为什么会设置里面会自动跑到下水道设置呀

### ISSUE THREAD

**Issue by Dacxy** [44451516/XIVSlothCombo#41]
我上传了录屏，当在设置时，滚轮向下或者拖动时会强制把界面调成下水道的设置里面

https://github.com/44451516/XIVSlothCombo/assets/41190242/06c3b4b6-8770-481b-9273-0e04957100d6

**Comment by 44451516** [comment]
综合设置里面，隐藏选项关掉
