### ISSUE TITLE
骑士的简单模式和高级模式翻译反了

### ISSUE THREAD

**Issue by ccds0614** [44451516/XIVSlothCombo#46]
[XIVSlothCombo/blob/main/XIVSlothCombo/Combos/CustomComboPreset.cs](https://github.com/44451516/XIVSlothCombo/blob/main/XIVSlothCombo/Combos/CustomComboPreset.cs)

2130行、2135行、2140行、2193行，骑士简单模式和骑士高级模式翻译反了，实际表现为高级模式一个选项没有，简单模式一堆选项

**Comment by 44451516** [comment]
已更新
