### ISSUE TITLE
离线和线上都无法安装

### ISSUE THREAD

**Issue by Crozz333** [44451516/XIVSlothCombo#47]
![SQQAXPJW}(641}ZX(DD}(6E](https://github.com/44451516/XIVSlothCombo/assets/133202759/9e305bf0-57a8-429c-9f33-8e733c13005a)
已经用了反屏蔽插件也不行，请问如何解决

**Comment by Crozz333** [comment]
人在国外也试过挂国内梯子也试了不挂梯子，之前还没遇到过这种情况

**Comment by 44451516** [comment]
现在在试试
