### ISSUE TITLE
推薦一個新的機工士十分鐘循環，請看一下，謝謝！

### ISSUE THREAD

**Issue by virginia0514** [44451516/XIVSlothCombo#48]
![20231224121220](https://github.com/44451516/XIVSlothCombo/assets/81150167/e195f277-d681-47d7-be6c-d470eb6677c0)
非常好的火電釋放
詳細演示在B站地址：BV1VG4y1E78h 

[机工士6.X标准循环(更新6.4/6.5)](https://www.bilibili.com/video/BV1VG4y1E78h/?share_source=copy_web&vd_source=d5b2f3f62fee8a37b58fdd68795bc5de)

**Comment by 44451516** [comment]
已阅！
