### ISSUE TITLE
白魔的简单aoe治疗

### ISSUE THREAD

**Issue by Potioner** [44451516/XIVSlothCombo#49]
从SlothCombo更新到SlothComboX之后，如果勾选简单aoe治疗，在没有医济buff的情况下且使用其他gcd技能过程中，该combo键会短暂的变回医治，在gcd彻底转好之后才会变成医济。这就导致如果在其他技能gcd后半段提前按下该combo键，会让医治进入技能队列而非医济。
更新之前是没有这个问题的，只会在身上有医济buff的情况下该combo键才会变成医治。
不知道这个算不算是一个bug，但是确实会影响一些手感。

**Comment by 44451516** [comment]
3.0.19.2 fix
