### ISSUE TITLE
关于3.18.53战士的选项bug

### ISSUE THREAD

**Issue by saconnage** [44451516/XIVSlothCombo#51]
在版本3.18.53里，战士有个选项#729裂石飞环/地毁人亡
描述中的 当 原初的解放 小于30秒时开始留资源。这一点并沒有生效。实际使用时，不论任何时间点，只要兽魂超过设置的仪表盘值，就开始消耗兽魂，并沒有开始留资源

**Comment by 44451516** [comment]
描述有问题应该是：超过设置的仪表盘就会释放

**Comment by 44451516** [comment]
如果你觉得需要这个功能 欢迎Fork 自行修改。
