### ISSUE TITLE
战士在未学习狂魂的情况下出现的问题

### ISSUE THREAD

**Issue by windandsword** [44451516/XIVSlothCombo#52]
战士在未学习狂魂的情况下，副本中使用单体combo会在使用战壕buff后衔接AOE技能“混沌旋风”，而不是正常使用单体技能“裂石飞环”，以上情况是在“暴风斩连击”选项下勾选了“裂石飞环/地毁人亡”的选项出现的bug问题

**Comment by 44451516** [comment]
非bug，逻辑如此，混沌旋风直爆优于裂石飞环
