### ISSUE TITLE
3.0.19.0版本SCX机工热冲击替换失效

### ISSUE THREAD

**Issue by tachibanatomoyo** [44451516/XIVSlothCombo#54]
高级模式-单目标，仅勾选<热冲击选项>无法将分裂弹替换为热冲击，必须同时勾选<虹吸弹/弹射>选项才会实现替换，但此时一键循环中会在热冲击期间强制插入虹吸弹或弹射，按其他能力技会卡gcd，不够灵活。之前版本没有此问题，希修复

**Comment by 44451516** [comment]
3.0.19.1 -> MCH: HeatBlast Option Control
