### ISSUE TITLE
关于绝枪战士的烈牙连击CD选项

### ISSUE THREAD

**Issue by zflr** [44451516/XIVSlothCombo#55]
强烈建议将绝枪战士的烈牙连击CD选项改成 添加到猛禽爪上面 这样在某些BOSS上天 或者资源不足的时候可以手动延后资倾斜，使得绝枪的手感更好 而不是现在的子弹连转好了就必须打出去  希望能给予改进 谢谢

**Comment by 44451516** [comment]
我的中文不是很好。你可以录个视频吗？

**Comment by zflr** [comment]
录了视频太大了上传不了啊.....

**Comment by 44451516** [comment]
3.0.19.3 fix
