### ISSUE TITLE
XIV SlothComboX v3.0.19.3 MCH combo problem

### ISSUE THREAD

**Issue by DEXDIVERS** [44451516/XIVSlothCombo#56]
在最新的版本里，机工高级模式-单目标模式下，连招的第一下[热分裂弹]会无法进行预输入。
每一次连招的第一下都需要等其公CD完全转好后才能使用，如同游戏本身的技能宏一般。游戏允许普通的技能参与预输入。我们可以在GCD快转好的前0.5秒左右提前按下下一个想要释放的技能。此时按下的技能会进入队列，当GCD彻底冷却完成后，下一个技能便会直接释放出去。预输入也是100%GCD利用率的必要条件。但是热分裂弹目前宛如一个宏技能一样，无法提前预输入。
我已经确保拖出到技能栏的是分裂弹而非热分裂弹。
In the latest version, the MCH section is having a bug right now. The Heated Split Shot can't typeahead to the game. To be more specific, the skill combos of all other classes currently don't seem to have this problem. The other skills of the machinist don’t have this problem either. For each 123 combo, the first [Heated Split Shot] will require waiting for its GCD to completely cool down. After the fully cool down, then you can press it to respond. It is weird and will heavily make the machinist's combo feel worse. But other skills did not show this problem. Such as a air anchor follow by a drill. We can type the drill before the GCD fully cooldown. Generally, when the air anchor is released and the GCD cooling circle reaches the last quarter, we can already press the drill button at this time. When the GCD cooling is completed, the drill will be released instantly. Type-ahead is one of the inherent features of the game. Ordinary skills can be released by inputting about half a second in advance. But macros are not allowed to participate in typeahead. When we want to use macro skills, we must ensure that the current character is in a free state - that is, the GCD is completely cooled down. Even if the GCD's cooldown is only the last 0.01 seconds, the macro skills we press during this period are invalid. At this time, the mechanic's [Heated Split Shot] in the advanced single target mode had a problem similar to the macro skill. It cannot be pre-typed into the game like a normal skill.
And this problem does not occur in Machinist's single target simple mode. I have reinstalled SCX and restarted the game many times. I can also make sure that the one currently on my skill bar is the low-level [Split Shot]. Please check and see if this problem can be solved? Thank you so much for your work.

**Comment by 44451516** [comment]
[3.0.19.4 -> FIX MCH GCD BUG](https://github.com/44451516/XIVSlothCombo/commit/c485f29cecd58de2840dbd87364c3609ef37b87c)

**Comment by DEXDIVERS** [comment]
God thank you so much.
