### ISSUE TITLE
绝枪连击

### ISSUE THREAD

**Issue by Grassdg** [44451516/XIVSlothCombo#60]
1 绝枪"替换利刃斩"和"爆发击防止子弹溢出"能不能分开处理?主要问题
2 能否在一键连击的时候不改变技能图标?或者能否做出自定义的连击?(似乎不太可能)

**Comment by 44451516** [comment]
1、不知道什么意思
2、自定义循环在测试中欢迎加群测试，群号自己找找（不是那个老群）
